// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBoNI6rNstDKZXRx6ZnKshCxO6KZwJAD0',
    appId: '1:1035194485265:web:2da8828442aee23fda3fb0',
    messagingSenderId: '1035194485265',
    projectId: 'doctorappointmentapp-efc65',
    authDomain: 'doctorappointmentapp-efc65.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-efc65.firebasestorage.app',
    measurementId: 'G-BXP7R5NP7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2pHvJlMAOf44mG2Ab8GSIWfkZYALqvA',
    appId: '1:1035194485265:android:c5ba0145125c2dd5da3fb0',
    messagingSenderId: '1035194485265',
    projectId: 'doctorappointmentapp-efc65',
    storageBucket: 'doctorappointmentapp-efc65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfRutGFfLSB3QydF7pVb3sf9jSfIdX1hU',
    appId: '1:1035194485265:ios:db3f790ba62a7498da3fb0',
    messagingSenderId: '1035194485265',
    projectId: 'doctorappointmentapp-efc65',
    storageBucket: 'doctorappointmentapp-efc65.firebasestorage.app',
    iosBundleId: 'com.example.citasMedicas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfRutGFfLSB3QydF7pVb3sf9jSfIdX1hU',
    appId: '1:1035194485265:ios:db3f790ba62a7498da3fb0',
    messagingSenderId: '1035194485265',
    projectId: 'doctorappointmentapp-efc65',
    storageBucket: 'doctorappointmentapp-efc65.firebasestorage.app',
    iosBundleId: 'com.example.citasMedicas',
  );
}
